version: '3.8'
services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - ./chroma_data:/chroma/chroma_data
    ports:
      - "8000:8000"

  fastapi:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CHROMA_SERVER_URL=http://chroma:8000
    depends_on:
      - chroma